### ISSUE TITLE
Weekly Scrum - [March 6, 2020]

### ISSUE THREAD

**Issue by fatimahashi** [Benjamin-Bichel/GAMZ#14]
1. What have I done this week? (with link(s) to the relevant GitHub Issue(s))
2. What will I do next week? (with link(s) to the relevant GitHub Issue(s))
3. What is holding me back? (if applicable)

**Comment by Benjamin-Bichel** [comment]
Thx for reminder <3

**Comment by Benjamin-Bichel** [comment]
Just finished Refactoring around the code within the bringing it all together branch, essentially just more readable and orginized

**Comment by thomas7carriere** [comment]
1) Attempted work on issues #3 and #10, building the controllers for the application.
2) Continue work on and create additional controllers, adding further functionality.
3) Had a lot of difficulty getting the project and labs working from home, spent most of my time troubleshooting.

**Comment by fatimahashi** [comment]
1. Creates view #1. Updated controllers based on view template #3. Updated main classes
2. Add more views #23 Update main view page Log into redirect to other views #9. Add classes to have Professor submit recommendation.  
3. Pushing files into Github, most files were on local machine as we were using App Center for Continuous Integration.
