### ISSUE TITLE
Creation of Services

### ISSUE THREAD

**Issue by Benjamin-Bichel** [Benjamin-Bichel/GAMZ#19]
Creation of the services that will handle all information and data pipelining into the database

**Comment by Benjamin-Bichel** [comment]
This issue will be linked with the controller problem as well, information on creation style: https://dzone.com/articles/spring-boot-with-spring-data-jpa

**Comment by fatimahashi** [comment]
Pushing to Milestone 2.

**Comment by Benjamin-Bichel** [comment]
It is slowly being assembled what services are needed

**Comment by fatimahashi** [comment]
@fatimahashi added ProfService #62 , ApplicationService #60 
@Benjamin-Bichel added FieldService #64
