### ISSUE TITLE
Validation of Horoku With Git

### ISSUE THREAD

**Issue by Benjamin-Bichel** [Benjamin-Bichel/GAMZ#21]
Same problem with App center

**Comment by fatimahashi** [comment]
@thomas7carriere I think we need to specify where Travis is being deployed to. By default, it's travis-ci.org but we're running on travis-ci.com. To fix this we have to run travis encrypt $(heroku auth:token) --add deploy.api_key --pro.

Can you follow the guidance from instructions below.
https://github.com/travis-ci/travis-ci/issues/10018

Also more info here: https://docs.travis-ci.com/user/deployment/heroku/#running-commands

**Comment by fatimahashi** [comment]
Heroku is successfully being deployed.
