### ISSUE TITLE
Implementation of pdfbox, docx4j

### ISSUE THREAD

**Issue by Benjamin-Bichel** [Benjamin-Bichel/GAMZ#22]
This requires one to read all information from the documents and then interpret it into the data model

**Comment by Benjamin-Bichel** [comment]
openpdf was discovered to be a better option in the long run, utlized in another project

**Comment by fatimahashi** [comment]
@Benjamin-Bichel Seems like an enhancement - not sure if it's required to implement base functionality at this moment.

**Comment by Benjamin-Bichel** [comment]
This is being changed around to just accept pdfs, and will display the cv in a new tab
