### ISSUE TITLE
Problems parsing the prof, login html pages

### ISSUE THREAD

**Issue by Benjamin-Bichel** [Benjamin-Bichel/GAMZ#24]
Currently when loading those pages they will not display, parsing error was hit

**Comment by fatimahashi** [comment]
Views are commented out - to be implemented in Milestone 2.

**Comment by fatimahashi** [comment]
Feature for Milestone 2.

**Comment by fatimahashi** [comment]
Fixed when login view was updated (see pull request #30).
Able to parse all 3 views
