### ISSUE TITLE
Weekly SCRUM - [March 18, 2020]

### ISSUE THREAD

**Issue by fatimahashi** [Benjamin-Bichel/GAMZ#28]
Answer the following per member:

1. What have I done this week? (with link(s) to the relevant GitHub Issue(s))
2. What will I do next week? (with link(s) to the relevant GitHub Issue(s))
3. What is holding me back? (if applicable)

**Comment by Benjamin-Bichel** [comment]
This week had been a tough one with the school closing down and having to reorganize:
I was unable to accomplish a lot this wee but what was done, was the validation of the h2 database and being able to connect with it and view the data. Along with Fixing errors as arisen.

**Comment by fatimahashi** [comment]
1. Added a main login page (#30), fixed bugs regarding parsing through pages (#24), added Admin view (#23), linked/fixed applicant (#34) and prof (#35) forms in PR #40.  

2. For the next milestone, working on sending/receiving notifications #45, fixing admin view of submissions into tables (#47) , adding more fields to forms (#48)

3. We've had a small issue when using Travis (from using Travis-ci.org vs Travis-ci.com). Also as @Benjamin-Bichel mentioned, this week has been slowed down with campus shutting down.

**Comment by fatimahashi** [comment]
Closed for this milestone.
