### ISSUE TITLE
Creation Of Controllers

### ISSUE THREAD

**Issue by Benjamin-Bichel** [Benjamin-Bichel/GAMZ#3]
- MainController currently returns student.html view on localhost:8080
-  Needs updating
- When login button is pressed, nothing happens

**Comment by Benjamin-Bichel** [comment]
Need controllers to go with services, idea found here: https://dzone.com/articles/spring-boot-with-spring-data-jpa

**Comment by fatimahashi** [comment]
Completed in Milestone 1.
