### ISSUE TITLE
Weekly SCRUM - [April 3, 2020]

### ISSUE THREAD

**Issue by fatimahashi** [Benjamin-Bichel/GAMZ#59]
1. What have I done this week? (with link(s) to the relevant GitHub Issue(s))
2. What will I do next week? (with link(s) to the relevant GitHub Issue(s))
3. What is holding me back? (if applicable)

#2 not required.

**Comment by fatimahashi** [comment]
1. Resolved bug fixes in Applicant #42 and in Admin #43, updated views to now show data in tables #48, created ApplicantService #19, many attempts to configure authentication/roles #53 (not successful as spring Security kept redirecting me to the default login), created class diagram #58, README documentation. 
2. n/a  
3. The biggest setback for this final milestone was the time crunch - before moving onto the next step, there was feedback and issues from the previous milestones that I had to complete myself. For this reason, we were not able to complete parts of the functionality of the system (Prof to send final as well as enhanced features such as notifications, enable checkboxes, and use proper authentication (which I really wanted to successfully implement, I got really close). Overall although there were many setbacks, I think I learned some new skills in building web applications through trial and error as well as resources from Google and stackOverflow.

**Comment by Benjamin-Bichel** [comment]
1. Added functionality for profs to add and display all fields to the database, cleaned up the temporary folder within the project to remove old HTML
2.N/A
3. The biggest set back this week for me was also a time crunch with multiple projects this week due my time management skills were lackluster

**Comment by Benjamin-Bichel** [comment]
Reviewing the code once more it would take approximately, 6-12 hours to correctly full-stack deployment, add those features, as it would require some refactoring. Non-full-stack development approximately 3-7.

**Comment by Benjamin-Bichel** [comment]
Security is a whole other ball game, Fatima took lead on that front

**Comment by fatimahashi** [comment]
Done.

**Comment by fatimahashi** [comment]
@Benjamin-Bichel did some great work on the filtering & recommendation part.
