### ISSUE TITLE
Filtering 

### ISSUE THREAD

**Issue by Benjamin-Bichel** [Benjamin-Bichel/GAMZ#71]
Essentially, we need to allow the prof to filter trough applicants via the field, cgpa, ect, and same with the admin

**Comment by fatimahashi** [comment]
@Benjamin-Bichel Sure - are you thinking of having a single (or multiple) search bar?

Also keep in mind, filtering has to come with a select feature as well. Filter for an applicant, select the desired applicant, send to selected prof (for Admin page) or make recommendation (for Prof page).

**Comment by fatimahashi** [comment]
Closed - see PR #79
